### ISSUE TITLE
Multiple contracts causes issue with live sensor

### ISSUE THREAD

**Issue by akicker** [DarwinsBuddy/WienerNetzeSmartmeter#227]
Logger: custom_components.wnsm.live_sensor
Quelle: custom_components/wnsm/live_sensor.py:68
Integration: WienerNetzeSmartmeter (Dokumentation, Probleme)
Erstmals aufgetreten: 9. April 2024 um 21:46:21 (7 Vorkommnisse)
Zuletzt protokolliert: 09:46:20

**Please file an issue with this error** and (anonymized) payload in github {'hasSmartMeter': True, 'isDataDeleted': False, 'zaehlpunkt': 'AT001000000000000000xxxxxxxxxxxxxx', 'type': 'TAGSTROM', 'address': 'Adresse', 'zip': '1130'} {'consumptionYesterdayValue': 585, 'consumptionYesterdayValidated': True, 'consumptionYesterdayTimestamp': '2024-04-07T22:00:00.000Z', 'consumptionDayBeforeYesterdayValue': 495, 'consumptionDayBeforeYesterdayValidated': True, 'consumptionDayBeforeYesterdayTimestamp': '2024-04-06T22:00:00.000Z'} {'lastValue': 4019380, 'lastReading': '2024-04-08T22:00:00.000Z', 'lastValidated': True, 'lastType': '1-2:1.8.0'} {'optIn': True, 'consumptionAverage': 0, 'consumptionMinimum': 0, 'consumptionMaximum': 0}
Please file an issue with this error and (anonymized) payload in github {'hasSmartMeter': True, 'isDataDeleted': False, 'zaehlpunkt': 'AT001000000000000000xxxxxxxxxxxxxx', 'type': 'TAGSTROM', 'address': 'Adresse', 'zip': '1130'} {'consumptionDayBeforeYesterdayValue': 585, 'consumptionDayBeforeYesterdayValidated': True, 'consumptionDayBeforeYesterdayTimestamp': '2024-04-07T22:00:00.000Z'} {'lastValue': 4019380, 'lastReading': '2024-04-08T22:00:00.000Z', 'lastValidated': True, 'lastType': '1-2:1.8.0'} {'optIn': True, 'consumptionAverage': 0, 'consumptionMinimum': 0, 'consumptionMaximum': 0}
Please file an issue with this error and (anonymized) payload in github {'hasSmartMeter': True, 'isDataDeleted': False, 'zaehlpunkt': 'AT001000000000000000xxxxxxxxxxxxxx', 'type': 'TAGSTROM', 'address': 'Adresse', 'zip': '1130'} {'consumptionYesterdayValue': 505, 'consumptionYesterdayValidated': True, 'consumptionYesterdayTimestamp': '2024-04-08T22:00:00.000Z', 'consumptionDayBeforeYesterdayValue': 585, 'consumptionDayBeforeYesterdayValidated': True, 'consumptionDayBeforeYesterdayTimestamp': '2024-04-07T22:00:00.000Z'} {'lastValue': 4019885, 'lastReading': '2024-04-09T22:00:00.000Z', 'lastValidated': True, 'lastType': '1-2:1.8.0'} {'optIn': True, 'consumptionAverage': 0, 'consumptionMinimum': 0, 'consumptionMaximum': 0}

**Comment by MatthiasRei** [comment]
Today the smartmeter Webportal from Wienernetze is offline. It looks like something is going on there :)

**Comment by GeraldPape** [comment]
I have this error today,....
2024-04-12 08:26:01.016 ERROR (MainThread) [custom_components.wnsm.live_sensor] Unable to load consumption
2024-04-12 08:26:01.017 ERROR (MainThread) [custom_components.wnsm.live_sensor] Please file an issue with this error and
(anonymized) payload in github {'hasSmartMeter': True, 'isDataDeleted': False, 'name': 'Bezug', 'zaehlpunkt': 'AT00100000000000000010000xxxxxxx6', 'type': 'TAGSTROM', 'address': 'Straße 45, 1220 Wien', 'zip': '1220'} {'consumptionYesterdayValue': 705, 'consumptionYesterdayValidated': True, 'consumptionYesterdayTimestamp': '2024-04-10T22:00:00.000Z', 'consumptionDayBeforeYesterdayValue': 1563, 'consumptionDayBeforeYesterdayValidated': True, 'consumptionDayBeforeYesterdayTimestamp': '2024-04-09T22:00:00.000Z'} {'lastValue': 11138193, 'lastReading': '2024-04-11T22:00:00.000Z', 'lastValidated': True, 'lastType': '1-2:1.8.0'} {'optIn': True, 'consumptionAverage': 0, 'consumptionMinimum': 0, 'consumptionMaximum': 0}

**Comment by reox** [comment]
Maybe something changed in the API or it has temporary issues... I get more errors, but in general the import still works.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1268, in async_device_update
    await self.async_update()
  File "/config/custom_components/wnsm/live_sensor.py", line 29, in async_update
    zaehlpunkt = await self.get_zaehlpunkt(smartmeter)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/base_sensor.py", line 108, in get_zaehlpunkt
    zaehlpunkte = self.contracts2zaehlpunkte(contracts)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/base_sensor.py", line 93, in contracts2zaehlpunkte
    geschaeftspartner = contracts[0]["geschaeftspartner"] if "geschaeftspartner" in contracts[0] else None
                                                                                    ~~~~~~~~~^^^
KeyError: 0
```

```
Traceback (most recent call last):
  File "/config/custom_components/wnsm/statistics_sensor.py", line 113, in async_update
    zaehlpunkt = await self.get_zaehlpunkt(smartmeter)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/base_sensor.py", line 108, in get_zaehlpunkt
    zaehlpunkte = self.contracts2zaehlpunkte(contracts)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/base_sensor.py", line 92, in contracts2zaehlpunkte
    raise RuntimeError(f"Cannot access Zaehlpunkt {self.zaehlpunkt}")
RuntimeError: Cannot access Zaehlpunkt AT[...]
```


```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1268, in async_device_update
    await self.async_update()
  File "/config/custom_components/wnsm/live_sensor.py", line 28, in async_update
    await self.hass.async_add_executor_job(smartmeter.login)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/api/client.py", line 125, in login
    code = self.credentials_login(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/api/client.py", line 75, in credentials_login
    raise SmartmeterLoginError("Login failed. Check username/password.")
custom_components.wnsm.api.errors.SmartmeterLoginError: Login failed. Check username/password.
```


```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1268, in async_device_update
    await self.async_update()
  File "/config/custom_components/wnsm/live_sensor.py", line 28, in async_update
    await self.hass.async_add_executor_job(smartmeter.login)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/api/client.py", line 124, in login
    url = self.load_login_page()
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/api/client.py", line 53, in load_login_page
    action = tree.xpath("(//form/@action)")[0]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by DarwinsBuddy** [comment]
Is this still a problem?
I checked my set up and couldn't find any concerning logs.
Something's definitely off with the API. I just want to re-confirm if it was a temporary fluke or there's something we can do from our side (if it still persists).
@akicker @MatthiasRei @GeraldPape @reox

**Comment by MatthiasRei** [comment]
No problems now 👍

**Comment by reox** [comment]
I guess that the API has some downtimes or sometimes returns not all data... The errors I collected above are probably things which could be programmed in a more resilient way, for example by checking returned data.
But as I said, the import still works for me!

**Comment by W-M-B** [comment]
> ich habe einen Smartmeter, allerdings 2 Zählpunkte - Verbrauch und Einspeisung Daten für den Verbrauch werden geladen, Einspeisung nicht! PS: im Webgui (https://smartmeter-web.wienernetze.at/) sind beide Daten vorhanden.

@akicker  if the problem is not related to topic of the issue, please create a new one and provide information that helps to understand the problem. or this is maybe related to
Hallo, wenn der Fehler mit den 2 Smartmeter nicht mit dem Titel zusammenhängt, bitte einen neuen Issue thread mit ausreichend Details beginnen. Eventuell hat es auch mit Issue 191 zu tun?


https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/issues/191

**Comment by akicker** [comment]
Mehrere Warnungen und Fehler nach dem Start:
Starting import of historical data. This might take some time.
wnsm: **Error** on device update!
Setup of sensor platform wnsm is taking over 10 seconds.
**FEHLER** Unable to load consumption
**FEHLER** Please file an issue with this error and (anonymized) payload in github ...

**Comment by akicker** [comment]
New WARNING since core 2024.5.1: HomeAssistantType was used from wnsm, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'wnsm' custom integration

**Comment by tschoerk** [comment]
Ok so figured it out after some tinkering. This problem only happens when there are two Zählpunkte. They way that the live sensor update works is that it gets the basic data from Wiener Netze, which includes the last value of the meter readings for the "main" or "favourite" Zählerpunkt. If the Zählerpunkt from the sensor and the "main" Zählerpunkt are identical then this value is used to update the sensor. 

If the second Zählerpunkt is updated, the base meter readings don't have the information for this Zählerpunkt, since it's not the "main" Zählerpunkt. So it tries to get the information by checking the consumption data, which shows the consumption starting from the chosen day, in this case for yesterday, to update the sensor with this value. This second method has several bugs though:

1. live_sensor.py checks if the return of get_consumption_raw has a field statistics `if ("values" in verbrauch_raw  and "statistics" in verbrauch_raw)`. The raw response has this field, but the method get_consumption_raw maps this response with ATTRS_VERBRAUCH_CALL, which removes the statistics, so it never gets past the if. Therefore the return of get_consumption_raw should be unmapped and simply return the response. So change the return of the method get_consumption_raw in base_sensor.py from `return translate_dict(response, ATTRS_VERBRAUCH_CALL)` to `return response`.
2. WienerNetze returns the consumption from yesterday only when the start date is set to the day before yesterday, maybe because the API excludes the given start day and returns data starting from the day after. Maybe it's depending on the time of day, but I tested several times and it never returns data, when the start day is yesterday. So the start date needs to be set two days before today, to get yesterday's consumption. So changing `verbrauch_raw = await self.get_consumption_raw(smartmeter, before(today()))` to `verbrauch_raw = await self.get_consumption_raw(smartmeter, before(before(today())))` in live_sensor.py should fix this. **This one is still a bit buggy though, since the update from wiener netze doesn't happen until several hours into the day (5 AM last night for example) and every call after midnight returns no data until the data is available and therefore throws hourly errors.**
3. Furthermore the safeget call to receive the average from the API response threw errors . Since safeget expects *args, there's no need to call this method with a list. Therefore the call should be changed from `avg = safeget(verbrauch_raw, [["statistics"], ["average"]])` to `avg = safeget(verbrauch_raw, "statistics", "average")`
4. Since the consumption is in Wh but the default unit for the sensors in HA is kWh the final state must be divided by 1000: `self._state = yesterdays_sum / 1000`

With all those fixes the daily live updates work with the second Zählpunkt. 

The inherent problem though is that the first and second Zählerpunkt give out completly different values, meaning the first one updates using the meter readings, so using the full consumption value since implementation of the meter and the second method only returns yesterdays consumption which are two different value types for the same sensor type.

So I had the idea to completely change how getting the value of the second Zählpunkt works. With a simple PUT call the second Zählerpunkt can be set as the "main" Zählerpunkt. Afterwards the calls for base_information and meter_readings return the full information regarding this one. Afterwards the first Zählerpunkt can be set as "main" again. That would give both sensors the same values.

Here is the call:
```
PUT https://api.wstw.at/gateway/WN_SMART_METER_PORTAL_API_B2C/1.0/kundennummer/{customer_id}/zaehlpunkt/default
Body: {"zaehlpunktNummer":"AT001000000000000000#############"}
```

So instead of making a pull request for the fixes stated above (you can find the fixes stated above in my repo https://github.com/tschoerk/WienerNetzeSmartmeter/tree/bugfix/loadConsumption if interested), I would work on the alternative method, since I think it makes much more sense that way. I will make a request when finished.

**Comment by tschoerk** [comment]
I tested different solutions with my proposed idea of changing the main or default zaehlerpunkt to get the meter readings, but I can't figure out how to do it properly in the async environment. There's a race condition when changing the default zaehlpunkt so both sensors get the same data. There is some wonky solution using asyncio.sleep(), but it's rather buggy. Maybe someone else has some ideas regarding that?

Anyway I will make a pull request for my proposed fixed above. Both values still provide the daily usage in different forms, so it's probably fine.

**Comment by DarwinsBuddy** [comment]
I'd currently not feel comfortable with merging this. Especially as we have for this kind of logic no integrated tests at hand.
So let's put this aside as WIP and focus on it when there is more input.

**Comment by tschoerk** [comment]
Thanks for all the merges today!

Regarding this issue: the way consumption is tracked with the live sensor is by getting the meterReadings from the default zaehlpunkt (call to zaehlpunkt/meterReadings - it's the data you see on the front page of the smart meter portal). 
If there are multiple zaehlpunkte (with a PV for example), it will try to get the other data from the consumption data (call to messdaten/{customer_id}/{zaehlpunkt}/verbrauchRaw). This current way has several bugs as described above (https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/issues/227#issuecomment-2104269374), and the fixes I list in that comment are what is fixed in #233 (with a little additional date fix regarding the time between midnight and early morning, since this is when the consumption is actually updated).

The difference between the two return values is that the meterReadings is a number which increases daily, since it gives back to current meter reading (e.g. 1000 yesterday, 1005 today, 1010 tomorrow) and the consumption call returns the actual daily usage (e.g. 10 yesterday, 5 today, 5 tomorrow). Both show the daily consumption but in different ways, but I think that's fine for now.

Regarding the race condition, I think it's a misunderstanding. My original idea to fix this issue was to switch the default zaehlpunkt back and forth via API call, so the both or multiple zaehlpunkte get the return value from the call to zaehlpunkt/meterReadings. This would standardize the return value, but since the sensors update in an async environment it was really buggy, especially regarding race conditions. For this idea I have not commited anything.

**Comment by akicker** [comment]
simultanous with **custom_components/wnsm/live_sensor.py:68** there comes a second error:
Logger: custom_components.wnsm.live_sensor
Quelle: **custom_components/wnsm/live_sensor.py:67**
Integration: WienerNetzeSmartmeter ([Dokumentation](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter), [Probleme](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/issues))
Erstmals aufgetreten: 17. Juli 2024 um 17:08:03 (16 Vorkommnisse)
Zuletzt protokolliert: 08:08:00

**Unable to load consumption**

**Comment by tschoerk** [comment]
Can you post the payload from the error and let me know what is the "default" zaehlpunkt at the Smart Meter Portal (then one that shows up on the main page and has a star in the zaehlpunkt overview). If you are up for it you could try to implement the changes via ssh in #233 and see if it fixes your issue.

**Comment by akicker** [comment]
what do you mean with payload from the error?
Already implemented changes via ssh in #233 - some improvements, but not did not solve all errors.

**Comment by DarwinsBuddy** [comment]
> Thanks for all the merges today!
> 
> Regarding this issue: the way consumption is tracked with the live sensor is by getting the meterReadings from the default zaehlpunkt (call to zaehlpunkt/meterReadings - it's the data you see on the front page of the smart meter portal). If there are multiple zaehlpunkte (with a PV for example), it will try to get the other data from the consumption data (call to messdaten/{customer_id}/{zaehlpunkt}/verbrauchRaw). This current way has several bugs as described above ([#227 (comment)](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/issues/227#issuecomment-2104269374)), and the fixes I list in that comment are what is fixed in #233 (with a little additional date fix regarding the time between midnight and early morning, since this is when the consumption is actually updated).
> 
> The difference between the two return values is that the meterReadings is a number which increases daily, since it gives back to current meter reading (e.g. 1000 yesterday, 1005 today, 1010 tomorrow) and the consumption call returns the actual daily usage (e.g. 10 yesterday, 5 today, 5 tomorrow). Both show the daily consumption but in different ways, but I think that's fine for now.
> 
> Regarding the race condition, I think it's a misunderstanding. My original idea to fix this issue was to switch the default zaehlpunkt back and forth via API call, so both or multiple zaehlpunkte get the return value from the call to zaehlpunkt/meterReadings. This would standardize the return value, but since the sensors update in an async environment it was really buggy, especially regarding race conditions. For this idea I have not commited anything.

I think I get it now @tschoerk.
Since I'd not rely on the API too much of Wiener Netze (it has been proven quite irrational sometimes, especially without proper documentation), write actions on the API, e.g. changing the default zaehlpunkt, might not be the best solution.
Also the updates of a zaehlpunkt are not necessarily coming in always at the same time. So those are assumptions that might not be true right now, and even if, are suspect to change in the future.

Is there another way of fixing this issue?


@akicker I guess @tschoerk means, if you've gotten some logs regarding the posted issue. What do you mean by "implement changes via ssh"?

**Comment by tschoerk** [comment]
> I think I get it now @tschoerk. Since I'd not rely on the API too much of Wiener Netze (it has been proven quite irrational sometimes, especially without proper documentation), write actions on the API, e.g. changing the default zaehlpunkt, might not be the best solution. Also the updates of a zaehlpunkt are not necessarily coming in always at the same time. So those are assumptions that might not be true right now, and even if, are suspect to change in the future.

Yes definitley, it's a wonky suggestion at best. 

> Is there another way of fixing this issue?

The question is what is the "live-sensor" supposed to represent? Should it be the current meter readings (so the total usage since starting the zaehlpunkt, which is shown on the main page of smart meter)? If so, maybe we could just grab the meter readings for each sensor sequentially when setting everything up (or asking the user to set the current meter readings manually) and then adding the daily consumption, so all sensors would grab the data the same way and all sensors would still have the current meter readings.

> @akicker I guess @tschoerk means, if you've gotten some logs regarding the posted issue. What do you mean by "implement changes via ssh"?

Exactly, do you have some logs regarding the error messages, so we get more details regarding your error messages. Implement changes via ssh means that he manually implemented my pull request in his home assistant instance.

**Comment by tschoerk** [comment]
I found a solution. The API call to zaehlpunkte/{customer_id}/{zaehlpunkt}/messwerte with the valueType METER_READ gives out the meter readings of the selected dates. This is implemented in the historical_data function of client.py, with a few bugs (wrong URL, etc. - since this function is not used anywhere, it didn't bother). So all Zaehlpunkte can get the current meter readings from the same call, making it much simpler and less error prone. I will work on it and update the pull request.

**Comment by akicker** [comment]
Additional info after implementing https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/pull/233):
now wnsm generates 2 suspicious sensors:
sensor.at001000000000000000100000xxxxxxx_at00100000000000000010000yyyyyyyy
sensor.at001000000000000000100000xxxxxxx_at00100000000000000010000yyyyyyyy_statistics
where 
sensor.at001000000000000000100000xxxxxxx is the primary Zählpunkt Grid In (Verbrauch)
sensor.at00100000000000000010000yyyyyyyy is the secondary Zählpunkt Grid Out (Einspeisung)
this results in an adiitional ERROR, solved by deactivating these 2 sensors
Maybe that can help to solve the remaining problem?

**Comment by tschoerk** [comment]
Never seen this one before. I could imagine that the existing data and sensors mess with the new implementation or the JSON looks completly different for you (I had that once with multiple contracts, each having one zaehlpunkt, instead of one contract with multiple contracts). I would suggest a full reset first and if that persists post a log, especially the json with all the zaehlpunkte:

1. Navigate to the energy configuration and remove the sensors for consumption and feed-in
![grafik](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/assets/16376109/dfcac803-47cd-4bbe-ace9-c3ce32c17885)
2. Remove the statistical data of the sensors
    - Navigate to Developer tools -> Services -> Recorder: Clean up entities
    - Select all sensors (start with AT001)
    - Deactivate `Domains to remove` and `Entity globs to remove`
    - Select `Days to keep` and select 0
    - Click on `Execute service`
![grafik](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/assets/16376109/7780a776-5c6e-4cf5-8c5d-bb40545d10ea)
3. Remove the integration
    - Navigate to [Integrationen](https://my.home-assistant.io/redirect/integrations/) and to the entry of `WienerNetzeSmartmeter`.
    - Select the 3 points for ALL entries and click `Delete`
![grafik](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/assets/16376109/a6786f46-1011-4220-93ab-75800590967e)
4. Navigate to Developer tools -> [Statistics](https://my.home-assistant.io/redirect/developer_statistics/)
    - Enter AT001 in the search above
    - For each entry, a button should appear on the right “Problems with this integration”
    - Click on it and select delete
5. Reboot HomeAssistant
6. Install the newest version with HACS
7. Implement #233 again
8. Reboot HomeAssistant
9. Add the integration `WienerNetzeSmartmeter` again

Now 4 entities should be found, two “normal” and two “statistics”. In the energy configuration, the statistics sensors can now be added again for consumption and feed-in so that everything is clearly visible on the energy dashboard.

If the problems still occur, a good starting point for identifying problems is to activate debug logging in the integration:
1. delete the entities in the integration
2. activate the debug logging
3. add the entities again using Add entry
4. deactivate the debug logging - a log should be downloaded automatically
5. post the relevant parts, i.e. error messages etc. here especially the outputs regarding zaehlpunkte. Maybe the JSON is built differently for you and needs to be taken care of.
![wnsm_integration](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/assets/16376109/9920f115-1f31-4db1-8ef0-776b92617f5e)

**Comment by akicker** [comment]
Did try your recommended steps unfortunately without success
as second run between 5 and 6 did delete the whole wnsm folder and did delete the suspicious sensors within core.entity_registry
finally did disable "Neu hinzugefügte Entitäten aktivieren" without any changes
Error retrieving data from smart meter api - Error: Zaehlpunkt at001000000000000000100000xxxxxx, at00100000000000000010000yyyyyyyy not found 
For now i did disable these sensors and will investigate some time to find out why these sensors are created,

**Comment by akicker** [comment]
reason found :-)
these entries are caused by the configuration file
  **vsm_zaehlpunktnummer:** at001000000000000000100000xxxxx, at00100000000000000010000yyyyyy
if i remove the second Zählpunkt there dublicate sensors of the primary are createed:
sensor.at001000000000000000100000xxxxx_2 and sensor.at001000000000000000100000xxxxx_statistics_2

**Comment by tschoerk** [comment]
Ah you are using the configuration.yaml and set the zaehlpunkte manually, but the config apparently only works with one zaehlpunkt. Never tested this one. Good catch! 

Just to make sure this is it, can you reset everything, delete the configuration.yaml and try to add the zaehlpunkte without the yaml file? The UI will ask you for username/password and add all zaehlpunkte which the smart meter returns. If it works without the configuration.yaml, I will then open a new issue for this specific issue and open a pull request to fix it.

**Comment by akicker** [comment]
Did remove configuration entries and anyhting is working fine 👍

**Comment by hwjf** [comment]
> I found a solution. The API call to zaehlpunkte/{customer_id}/{zaehlpunkt}/messwerte with the valueType METER_READ gives out the meter readings of the selected dates. This is implemented in the historical_data function of client.py, with a few bugs (wrong URL, etc. - since this function is not used anywhere, it didn't bother). So all Zaehlpunkte can get the current meter readings from the same call, making it much simpler and less error prone. I will work on it and update the pull request.

Fixed in #233

**Comment by tschoerk** [comment]
> I found a solution. The API call to zaehlpunkte/{customer_id}/{zaehlpunkt}/messwerte with the valueType METER_READ gives out the meter readings of the selected dates. This is implemented in the historical_data function of client.py, with a few bugs (wrong URL, etc. - since this function is not used anywhere, it didn't bother). So all Zaehlpunkte can get the current meter readings from the same call, making it much simpler and less error prone. I will work on it and update the pull request.

Implemented and fixed in #233
